global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "node-*.rules"
  - "service-*.rules"
  - "cloud-gateway.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 10s
    metrics_path: /metrics
    basic_auth:
      username: ${USERNAME}
      password: ${PASSWORD}
    static_configs:
      - targets: ['nodeexporter:9100']
        labels:
          group: 'master'
      - targets: ['node.tanggap.in:80']
        labels:
          group: 'frontend'
      - targets: ['node.jateng.tanggap.in:80']
        labels:
          group: 'frontend'
      - targets: ['spgdt.setyadhiputra.com:9100']
        labels:
          group: 'backend'
      - targets: ['node.gcp.tanggap.in:80']
        labels:
          group: 'backend'

  - job_name: 'cadvisor'
    scrape_interval: 10s
    metrics_path: /metrics
    basic_auth:
      username: ${USERNAME}
      password: ${PASSWORD}
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          group: 'master'
      - targets: ['cadvisor.tanggap.in:80']
        labels:
          group: 'frontend'
      - targets: ['cadvisor.jateng.tanggap.in:80']
        labels:
          group: 'frontend'
      - targets: ['cadvisor.gcp.tanggap.in:80']
        labels:
          group: 'backend'

  - job_name: 'traefik'
    scrape_interval: 10s
    metrics_path: /metrics
    basic_auth:
      username: ${USERNAME}
      password: ${PASSWORD}
    static_configs:
      - targets: ['tytyd.ddns.net:8080']
        labels:
          group: 'master'
      - targets: ['traefik.tanggap.in:8080']
        labels:
          group: 'frontend'
      - targets: ['traefik.jateng.tanggap.in:8080']
        labels:
          group: 'frontend'
      - targets: ['traefik.gcp.tanggap.id:8080']
        labels:
          group: 'backend'

  - job_name: 'dockerD'
    scrape_interval: 10s
    metrics_path: /metrics
    basic_auth:
      username: ${USERNAME}
      password: ${PASSWORD}
    static_configs:
      - targets: ['tytyd.ddns.net:9100']
        labels:
          group: 'master'
      - targets: ['api.setyadhiputra.com:9100']
        labels:
          group: 'frontend'
      - targets: ['dinkes.jateng.tanggap.in:9100']
        labels:
          group: 'frontend'
      - targets: ['spgdt.setyadhiputra.com:9101']
        labels:
          groups: 'backend'
      - targets: ['tanggap.setyadhiputra.com:9100']
        labels:
          groups: 'backend'

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']


alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'

#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']
